package org.universities.organization_educational_process.persistence.dao.services.interfaces.reference_book;

import org.universities.organization_educational_process.persistence.dao.services.interfaces.support_contracts.AddComponent;
import org.universities.organization_educational_process.persistence.dao.services.interfaces.support_contracts.ExistInDB;
import org.universities.organization_educational_process.persistence.dao.services.interfaces.support_contracts.FindAll;
import org.universities.organization_educational_process.persistence.model.reference_book.AcademicDegree;
import org.universities.organization_educational_process.persistence.requests.reference_book.AcademicDegreeRequest;

public interface AcademicDegreeSimpleService extends FindAll<AcademicDegree>, AddComponent<AcademicDegreeRequest>, ExistInDB<AcademicDegree> {
}
