package org.universities.organization_educational_process.persistence.dao.services.interfaces.reference_book;

import org.universities.organization_educational_process.persistence.dao.services.interfaces.support_contracts.AddComponent;
import org.universities.organization_educational_process.persistence.dao.services.interfaces.support_contracts.ExistInDB;
import org.universities.organization_educational_process.persistence.dao.services.interfaces.support_contracts.FindAll;
import org.universities.organization_educational_process.persistence.model.reference_book.AcademicTitle;
import org.universities.organization_educational_process.persistence.requests.reference_book.AcademicTitleRequest;

public interface AcademicTitleSimpleService extends FindAll<AcademicTitle>, AddComponent<AcademicTitleRequest>, ExistInDB<AcademicTitle> {
}
